language: expressio
sudo: required
before_install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
install: bash -ex .travis-opam.sh
after_install: bash -ex travis-ci.sh 
env:
  - OCAML_VERSION=4.06
script: 
    - cd src
    - make clean && make
