language : c
sudo : required
os:
  - linux
env :
  - OCAML_VERSION =4.02
before_install :
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
install :
  - export OCAML_VERSION=4.06
  - bash -ex .travis-ocaml.sh
  - opam install ocamlfind menhir
  - opam install llvm.3.8
  - export PATH=/usr/lib/llvm-3.8/bin:$PATH
before_script :
  - eval `opam config env `
script :
  - cd src
  - make clean && make