language: expressio
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
before_script: bash -ex .travis-opam.sh
script: bash -ex travis-ci.sh 
after_script: 
    - cd src
    - make clean && make
env:
  - OCAML_VERSION=4.06
